/**
 * Major world airports + cities for search autocomplete.
 * Tuple: [name, iata, city, countryCode, countryName, keywords?]
 */
export type AirportRow = [
  name: string,
  iata: string,
  city: string,
  countryCode: string,
  countryName: string,
  keywords?: string[],
];

export const AIRPORT_ROWS: AirportRow[] = [
  // Indonesia
  ["Soekarno-Hatta", "CGK", "Jakarta", "ID", "Indonesia"],
  ["Halim Perdanakusuma", "HLP", "Jakarta", "ID", "Indonesia"],
  ["Ngurah Rai", "DPS", "Denpasar", "ID", "Indonesia", ["bali"]],
  ["Juanda", "SUB", "Surabaya", "ID", "Indonesia"],
  ["Yogyakarta International", "YIA", "Yogyakarta", "ID", "Indonesia", ["jogja"]],
  ["Adisutjipto", "JOG", "Yogyakarta", "ID", "Indonesia"],
  ["Kualanamu", "KNO", "Medan", "ID", "Indonesia"],
  ["Sultan Hasanuddin", "UPG", "Makassar", "ID", "Indonesia"],
  ["Husein Sastranegara", "BDO", "Bandung", "ID", "Indonesia"],
  ["Ahmad Yani", "SRG", "Semarang", "ID", "Indonesia"],
  ["Sultan Mahmud Badaruddin II", "PLM", "Palembang", "ID", "Indonesia"],
  ["Sultan Aji Muhammad Sulaiman", "BPN", "Balikpapan", "ID", "Indonesia"],
  ["Sam Ratulangi", "MDC", "Manado", "ID", "Indonesia"],
  ["Zainuddin Abdul Madjid", "LOP", "Lombok", "ID", "Indonesia"],
  ["Sultan Iskandar Muda", "BTJ", "Banda Aceh", "ID", "Indonesia"],
  ["Supadio", "PNK", "Pontianak", "ID", "Indonesia"],
  ["Hang Nadim", "BTH", "Batam", "ID", "Indonesia"],
  ["Sultan Syarif Kasim II", "PKU", "Pekanbaru", "ID", "Indonesia"],
  ["Minangkabau", "PDG", "Padang", "ID", "Indonesia"],
  ["Komodo", "LBJ", "Labuan Bajo", "ID", "Indonesia"],
  ["El Tari", "KOE", "Kupang", "ID", "Indonesia"],
  ["Frans Kaisiepo", "BIK", "Biak", "ID", "Indonesia"],
  ["Sentani", "DJJ", "Jayapura", "ID", "Indonesia"],
  ["Pattimura", "AMQ", "Ambon", "ID", "Indonesia"],

  // Egypt
  ["Cairo International", "CAI", "Cairo", "EG", "Mesir", ["kairo", "cairo", "mesir", "egypt"]],
  ["Sphinx International", "SPX", "Cairo", "EG", "Mesir", ["giza"]],
  ["Hurghada", "HRG", "Hurghada", "EG", "Mesir"],
  ["Sharm El Sheikh", "SSH", "Sharm El Sheikh", "EG", "Mesir", ["sharm"]],
  ["Luxor", "LXR", "Luxor", "EG", "Mesir"],
  ["Borg El Arab", "HBE", "Alexandria", "EG", "Mesir", ["alexandria", "iskandariyah"]],
  ["Aswan", "ASW", "Aswan", "EG", "Mesir"],
  ["Mars Alam", "RMF", "Marsa Alam", "EG", "Mesir"],

  // Saudi Arabia
  ["King Abdulaziz", "JED", "Jeddah", "SA", "Arab Saudi", ["jedda", "mekkah", "makkah"]],
  ["King Khalid", "RUH", "Riyadh", "SA", "Arab Saudi"],
  ["Prince Mohammad Bin Abdulaziz", "MED", "Madinah", "SA", "Arab Saudi", ["medina"]],
  ["King Fahd", "DMM", "Dammam", "SA", "Arab Saudi"],
  ["Abha", "AHB", "Abha", "SA", "Arab Saudi"],
  ["Taif", "TIF", "Taif", "SA", "Arab Saudi"],
  ["Tabuk", "TUU", "Tabuk", "SA", "Arab Saudi"],
  ["Yanbu", "YNB", "Yanbu", "SA", "Arab Saudi"],

  // UAE / Gulf
  ["Dubai International", "DXB", "Dubai", "AE", "UEA"],
  ["Al Maktoum", "DWC", "Dubai", "AE", "UEA"],
  ["Abu Dhabi International", "AUH", "Abu Dhabi", "AE", "UEA"],
  ["Sharjah", "SHJ", "Sharjah", "AE", "UEA"],
  ["Hamad International", "DOH", "Doha", "QA", "Qatar"],
  ["Bahrain International", "BAH", "Manama", "BH", "Bahrain"],
  ["Kuwait International", "KWI", "Kuwait City", "KW", "Kuwait"],
  ["Muscat International", "MCT", "Muscat", "OM", "Oman"],
  ["Salalah", "SLL", "Salalah", "OM", "Oman"],

  // Levant / MENA
  ["Queen Alia", "AMM", "Amman", "JO", "Yordania", ["jordan"]],
  ["Aqaba", "AQJ", "Aqaba", "JO", "Yordania"],
  ["Beirut–Rafic Hariri", "BEY", "Beirut", "LB", "Lebanon"],
  ["Ben Gurion", "TLV", "Tel Aviv", "IL", "Israel"],
  ["Mohammed V", "CMN", "Casablanca", "MA", "Maroko", ["morocco"]],
  ["Marrakech Menara", "RAK", "Marrakech", "MA", "Maroko"],
  ["Tunis–Carthage", "TUN", "Tunis", "TN", "Tunisia"],
  ["Houari Boumediene", "ALG", "Algiers", "DZ", "Aljazair", ["algeria"]],
  ["Tripoli Mitiga", "MJI", "Tripoli", "LY", "Libya"],
  ["Khartoum", "KRT", "Khartoum", "SD", "Sudan"],
  ["Addis Ababa Bole", "ADD", "Addis Ababa", "ET", "Ethiopia"],
  ["Jomo Kenyatta", "NBO", "Nairobi", "KE", "Kenya"],
  ["Murtala Muhammed", "LOS", "Lagos", "NG", "Nigeria"],
  ["OR Tambo", "JNB", "Johannesburg", "ZA", "Afrika Selatan"],
  ["Cape Town", "CPT", "Cape Town", "ZA", "Afrika Selatan"],

  // SE Asia
  ["Changi", "SIN", "Singapore", "SG", "Singapura"],
  ["Kuala Lumpur International", "KUL", "Kuala Lumpur", "MY", "Malaysia", ["klia"]],
  ["Penang", "PEN", "Penang", "MY", "Malaysia"],
  ["Kota Kinabalu", "BKI", "Kota Kinabalu", "MY", "Malaysia"],
  ["Suvarnabhumi", "BKK", "Bangkok", "TH", "Thailand"],
  ["Don Mueang", "DMK", "Bangkok", "TH", "Thailand"],
  ["Phuket", "HKT", "Phuket", "TH", "Thailand"],
  ["Chiang Mai", "CNX", "Chiang Mai", "TH", "Thailand"],
  ["Ninoy Aquino", "MNL", "Manila", "PH", "Filipina"],
  ["Mactan–Cebu", "CEB", "Cebu", "PH", "Filipina"],
  ["Tan Son Nhat", "SGN", "Ho Chi Minh City", "VN", "Vietnam", ["saigon"]],
  ["Noi Bai", "HAN", "Hanoi", "VN", "Vietnam"],
  ["Da Nang", "DAD", "Da Nang", "VN", "Vietnam"],
  ["Phnom Penh", "PNH", "Phnom Penh", "KH", "Kamboja"],
  ["Siem Reap Angkor", "SAI", "Siem Reap", "KH", "Kamboja"],
  ["Yangon", "RGN", "Yangon", "MM", "Myanmar"],
  ["Bandaranaike", "CMB", "Colombo", "LK", "Sri Lanka"],
  ["Velana", "MLE", "Malé", "MV", "Maldives", ["maldives", "male"]],

  // East Asia
  ["Hong Kong International", "HKG", "Hong Kong", "HK", "Hong Kong"],
  ["Macau", "MFM", "Macau", "MO", "Macau"],
  ["Taiwan Taoyuan", "TPE", "Taipei", "TW", "Taiwan"],
  ["Kaohsiung", "KHH", "Kaohsiung", "TW", "Taiwan"],
  ["Incheon", "ICN", "Seoul", "KR", "Korea Selatan"],
  ["Gimpo", "GMP", "Seoul", "KR", "Korea Selatan"],
  ["Busan Gimhae", "PUS", "Busan", "KR", "Korea Selatan"],
  ["Narita", "NRT", "Tokyo", "JP", "Jepang"],
  ["Haneda", "HND", "Tokyo", "JP", "Jepang"],
  ["Kansai", "KIX", "Osaka", "JP", "Jepang"],
  ["Chubu Centrair", "NGO", "Nagoya", "JP", "Jepang"],
  ["Fukuoka", "FUK", "Fukuoka", "JP", "Jepang"],
  ["New Chitose", "CTS", "Sapporo", "JP", "Jepang"],
  ["Beijing Capital", "PEK", "Beijing", "CN", "China"],
  ["Beijing Daxing", "PKX", "Beijing", "CN", "China"],
  ["Shanghai Pudong", "PVG", "Shanghai", "CN", "China"],
  ["Shanghai Hongqiao", "SHA", "Shanghai", "CN", "China"],
  ["Guangzhou Baiyun", "CAN", "Guangzhou", "CN", "China"],
  ["Shenzhen Bao'an", "SZX", "Shenzhen", "CN", "China"],
  ["Chengdu Tianfu", "TFU", "Chengdu", "CN", "China"],
  ["Xi'an Xianyang", "XIY", "Xi'an", "CN", "China"],
  ["Hangzhou Xiaoshan", "HGH", "Hangzhou", "CN", "China"],

  // South Asia
  ["Indira Gandhi", "DEL", "Delhi", "IN", "India"],
  ["Chhatrapati Shivaji", "BOM", "Mumbai", "IN", "India"],
  ["Kempegowda", "BLR", "Bengaluru", "IN", "India", ["bangalore"]],
  ["Rajiv Gandhi", "HYD", "Hyderabad", "IN", "India"],
  ["Chennai", "MAA", "Chennai", "IN", "India", ["madras"]],
  ["Netaji Subhas Chandra Bose", "CCU", "Kolkata", "IN", "India", ["calcutta"]],
  ["Cochin", "COK", "Kochi", "IN", "India"],
  ["Goa Dabolim", "GOI", "Goa", "IN", "India"],
  ["Allama Iqbal", "LHE", "Lahore", "PK", "Pakistan"],
  ["Jinnah", "KHI", "Karachi", "PK", "Pakistan"],
  ["Islamabad", "ISB", "Islamabad", "PK", "Pakistan"],
  ["Hazrat Shahjalal", "DAC", "Dhaka", "BD", "Bangladesh"],
  ["Tribhuvan", "KTM", "Kathmandu", "NP", "Nepal"],

  // Turkey / Caucasus / Central Asia
  ["Istanbul Airport", "IST", "Istanbul", "TR", "Turki"],
  ["Istanbul Sabiha Gökçen", "SAW", "Istanbul", "TR", "Turki", ["sabiha"]],
  ["Ankara Esenboğa", "ESB", "Ankara", "TR", "Turki"],
  ["Antalya", "AYT", "Antalya", "TR", "Turki"],
  ["Izmir Adnan Menderes", "ADB", "Izmir", "TR", "Turki"],
  ["Tbilisi", "TBS", "Tbilisi", "GE", "Georgia"],
  ["Heydar Aliyev", "GYD", "Baku", "AZ", "Azerbaijan"],
  ["Almaty", "ALA", "Almaty", "KZ", "Kazakhstan"],
  ["Tashkent", "TAS", "Tashkent", "UZ", "Uzbekistan"],

  // Europe
  ["Heathrow", "LHR", "London", "GB", "Inggris"],
  ["Gatwick", "LGW", "London", "GB", "Inggris"],
  ["Stansted", "STN", "London", "GB", "Inggris"],
  ["Manchester", "MAN", "Manchester", "GB", "Inggris"],
  ["Edinburgh", "EDI", "Edinburgh", "GB", "Inggris"],
  ["Dublin", "DUB", "Dublin", "IE", "Irlandia"],
  ["Charles de Gaulle", "CDG", "Paris", "FR", "Prancis"],
  ["Orly", "ORY", "Paris", "FR", "Prancis"],
  ["Nice Côte d'Azur", "NCE", "Nice", "FR", "Prancis"],
  ["Amsterdam Schiphol", "AMS", "Amsterdam", "NL", "Belanda"],
  ["Frankfurt", "FRA", "Frankfurt", "DE", "Jerman"],
  ["Munich", "MUC", "Munich", "DE", "Jerman"],
  ["Berlin Brandenburg", "BER", "Berlin", "DE", "Jerman"],
  ["Düsseldorf", "DUS", "Düsseldorf", "DE", "Jerman"],
  ["Zurich", "ZRH", "Zurich", "CH", "Swiss"],
  ["Geneva", "GVA", "Geneva", "CH", "Swiss"],
  ["Vienna", "VIE", "Vienna", "AT", "Austria"],
  ["Brussels", "BRU", "Brussels", "BE", "Belgia"],
  ["Copenhagen", "CPH", "Copenhagen", "DK", "Denmark"],
  ["Stockholm Arlanda", "ARN", "Stockholm", "SE", "Swedia"],
  ["Oslo Gardermoen", "OSL", "Oslo", "NO", "Norwegia"],
  ["Helsinki-Vantaa", "HEL", "Helsinki", "FI", "Finlandia"],
  ["Lisbon", "LIS", "Lisbon", "PT", "Portugal"],
  ["Porto", "OPO", "Porto", "PT", "Portugal"],
  ["Adolfo Suárez Madrid-Barajas", "MAD", "Madrid", "ES", "Spanyol"],
  ["Barcelona-El Prat", "BCN", "Barcelona", "ES", "Spanyol"],
  ["Málaga", "AGP", "Málaga", "ES", "Spanyol"],
  ["Palma de Mallorca", "PMI", "Palma", "ES", "Spanyol"],
  ["Ibiza", "IBZ", "Ibiza", "ES", "Spanyol"],
  ["Leonardo da Vinci–Fiumicino", "FCO", "Roma", "IT", "Italia", ["rome"]],
  ["Milan Malpensa", "MXP", "Milan", "IT", "Italia"],
  ["Milan Linate", "LIN", "Milan", "IT", "Italia"],
  ["Napoli Capodichino", "NAP", "Napoli", "IT", "Italia", ["naples"]],
  ["Venice Marco Polo", "VCE", "Venice", "IT", "Italia"],
  ["Athens", "ATH", "Athens", "GR", "Yunani"],
  ["Santorini", "JTR", "Santorini", "GR", "Yunani"],
  ["Warsaw Chopin", "WAW", "Warsaw", "PL", "Polandia"],
  ["Prague Václav Havel", "PRG", "Prague", "CZ", "Ceko"],
  ["Budapest Ferenc Liszt", "BUD", "Budapest", "HU", "Hungaria"],
  ["Bucharest Henri Coandă", "OTP", "Bucharest", "RO", "Rumania"],
  ["Sofia", "SOF", "Sofia", "BG", "Bulgaria"],
  ["Belgrade Nikola Tesla", "BEG", "Belgrade", "RS", "Serbia"],
  ["Zagreb", "ZAG", "Zagreb", "HR", "Kroasia"],
  ["Moscow Sheremetyevo", "SVO", "Moscow", "RU", "Rusia"],
  ["Moscow Domodedovo", "DME", "Moscow", "RU", "Rusia"],
  ["Pulkovo", "LED", "Saint Petersburg", "RU", "Rusia"],

  // Americas
  ["John F. Kennedy", "JFK", "New York", "US", "Amerika Serikat", ["nyc"]],
  ["Newark Liberty", "EWR", "New York", "US", "Amerika Serikat"],
  ["LaGuardia", "LGA", "New York", "US", "Amerika Serikat"],
  ["Los Angeles", "LAX", "Los Angeles", "US", "Amerika Serikat"],
  ["San Francisco", "SFO", "San Francisco", "US", "Amerika Serikat"],
  ["Chicago O'Hare", "ORD", "Chicago", "US", "Amerika Serikat"],
  ["Hartsfield–Jackson Atlanta", "ATL", "Atlanta", "US", "Amerika Serikat"],
  ["Dallas/Fort Worth", "DFW", "Dallas", "US", "Amerika Serikat"],
  ["Miami", "MIA", "Miami", "US", "Amerika Serikat"],
  ["Seattle–Tacoma", "SEA", "Seattle", "US", "Amerika Serikat"],
  ["Denver", "DEN", "Denver", "US", "Amerika Serikat"],
  ["Boston Logan", "BOS", "Boston", "US", "Amerika Serikat"],
  ["Washington Dulles", "IAD", "Washington", "US", "Amerika Serikat"],
  ["Honolulu", "HNL", "Honolulu", "US", "Amerika Serikat", ["hawaii"]],
  ["Toronto Pearson", "YYZ", "Toronto", "CA", "Kanada"],
  ["Vancouver", "YVR", "Vancouver", "CA", "Kanada"],
  ["Montréal–Trudeau", "YUL", "Montreal", "CA", "Kanada"],
  ["Mexico City", "MEX", "Mexico City", "MX", "Meksiko"],
  ["Cancún", "CUN", "Cancún", "MX", "Meksiko"],
  ["São Paulo–Guarulhos", "GRU", "São Paulo", "BR", "Brasil"],
  ["Rio de Janeiro–Galeão", "GIG", "Rio de Janeiro", "BR", "Brasil"],
  ["Buenos Aires Ezeiza", "EZE", "Buenos Aires", "AR", "Argentina"],
  ["Jorge Chávez", "LIM", "Lima", "PE", "Peru"],
  ["El Dorado", "BOG", "Bogotá", "CO", "Kolombia"],
  ["Santiago", "SCL", "Santiago", "CL", "Chile"],

  // Oceania
  ["Sydney Kingsford Smith", "SYD", "Sydney", "AU", "Australia"],
  ["Melbourne", "MEL", "Melbourne", "AU", "Australia"],
  ["Brisbane", "BNE", "Brisbane", "AU", "Australia"],
  ["Perth", "PER", "Perth", "AU", "Australia"],
  ["Adelaide", "ADL", "Adelaide", "AU", "Australia"],
  ["Auckland", "AKL", "Auckland", "NZ", "Selandia Baru"],
  ["Christchurch", "CHC", "Christchurch", "NZ", "Selandia Baru"],
  ["Nadi", "NAN", "Nadi", "FJ", "Fiji"],
];
